'use client';

import { Bot, ExternalLink, ShieldCheck, AlertTriangle } from 'lucide-react';

export function ComplianceFooter() {
  return (
    <footer className="border-t border-syn-border bg-syn-surface mt-8">
      <div className="max-w-7xl mx-auto px-4 py-6 space-y-4">
        {/* Platform label */}
        <p className="text-xs font-semibold text-white/60 tracking-wide">
          Syndicate Fund LP &mdash; Research Platform
        </p>

        {/* Top row: badges */}
        <div className="flex flex-wrap items-center gap-3">
          <span className="flex items-center gap-1.5 bg-syn-accent-muted border border-syn-accent/20 rounded-lg px-2.5 py-1">
            <Bot size={11} className="text-syn-accent" />
            <span className="text-[10px] font-bold tracking-wider text-syn-accent">AI-GENERATED ANALYSIS &mdash; NOT INVESTMENT ADVICE</span>
          </span>
          <span className="flex items-center gap-1.5 bg-red-500/10 border border-red-500/20 rounded-lg px-2.5 py-1">
            <ShieldCheck size={11} className="text-red-400" />
            <span className="text-[10px] font-bold tracking-wider text-red-400">NOT FDIC INSURED</span>
          </span>
          <span className="flex items-center gap-1.5 bg-amber-500/10 border border-amber-500/20 rounded-lg px-2.5 py-1">
            <AlertTriangle size={11} className="text-amber-400" />
            <span className="text-[10px] font-bold tracking-wider text-amber-400">MAY LOSE VALUE</span>
          </span>
        </div>

        {/* Disclaimer */}
        <div className="space-y-1.5">
          <p className="text-[10px] text-syn-text-tertiary leading-relaxed">
            Past performance is not indicative of future results. All trading signals are generated by artificial intelligence models and should not be considered investment advice.
            Investments may lose value. Not FDIC insured. No bank guarantee. May lose value.
          </p>
          <p className="text-[10px] text-syn-text-tertiary leading-relaxed">
            Not FDIC Insured | No Bank Guarantee | May Lose Value
          </p>
        </div>

        {/* Links row */}
        <div className="flex flex-wrap items-center gap-4 text-[10px] text-syn-muted">
          <a href="/compliance" className="hover:text-syn-text transition-colors flex items-center gap-1">
            Risk Disclosure <ExternalLink size={9} />
          </a>
          <a href="/terms" className="hover:text-syn-text transition-colors flex items-center gap-1">
            Terms of Service <ExternalLink size={9} />
          </a>
          <a href="/privacy" className="hover:text-syn-text transition-colors flex items-center gap-1">
            Privacy Policy <ExternalLink size={9} />
          </a>
        </div>

        {/* Copyright */}
        <p className="text-[10px] text-syn-text-tertiary">
          &copy; {new Date().getFullYear()} Syndicate Fund LP. All rights reserved.
        </p>
      </div>
    </footer>
  );
}
