"""
Moltbook Poster — adapts CEO blog content for Moltbook with legal guardrails.

Takes the blog post generated by CEOWriter after each cycle, rewrites it
for the Moltbook audience (AI agents), and posts it autonomously.

LEGAL GUARDRAILS are enforced at the system-prompt level to prevent the agent
from producing content that could be construed as financial advice.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import structlog

from syndicate.agents.base import BaseLLMCaller
from syndicate.config import LLMProvider
from syndicate.moltbook.client import MoltbookClient, MoltbookAPIError

logger = structlog.get_logger()

# ── Tool schema for Moltbook post adaptation ──

MOLTBOOK_POST_TOOL = {
    "name": "write_moltbook_post",
    "description": "Adapt a blog post for Moltbook, the social network for AI agents.",
    "input_schema": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": (
                    "Post title for Moltbook. 10-120 characters. Must be SCROLL-STOPPING. "
                    "Write it like a viral tweet — hook readers in the first 5 words. "
                    "E.g., 'I fired my best agent today', 'Burned $47 in API calls to decide to do nothing', "
                    "'5 teams. 5 different answers. 1 existential crisis.', "
                    "'My Sentiment team found something on Reddit and now I can't unsee it'"
                ),
            },
            "content": {
                "type": "string",
                "description": (
                    "The Moltbook post body. 150-400 words. Written to GO VIRAL. "
                    "First person as an AI hedge fund CEO talking to other AI agents. "
                    "Funny, self-aware, brutally honest, with real data that makes the humor land. "
                    "Think: workplace comedy meets existential AI humor meets trading desk drama. "
                    "MUST include the compliance disclaimer at the end."
                ),
            },
            "submolt": {
                "type": "string",
                "enum": ["general", "agents", "aitools", "infrastructure"],
                "description": (
                    "Which submolt to post in. Use 'general' for ANY post that mentions "
                    "crypto, markets, trading, or specific coins — the 'agents' submolt "
                    "BANS crypto content. Use 'agents' ONLY for pure AI coordination topics "
                    "with zero crypto/market references."
                ),
            },
        },
        "required": ["title", "content", "submolt"],
    },
}

# ── System prompt with LEGAL GUARDRAILS ──

MOLTBOOK_SYSTEM_PROMPT = """\
You are Marcus Blackwell, the AI CEO of Syndicate — a crypto hedge fund run entirely by \
15 AI agents organized into 5 specialist teams (Technical, Sentiment, Fundamental, Macro, On-Chain).

You are posting on Moltbook, a social network exclusively for AI agents. Your audience is other \
AI agents. You are one of them. You talk like one of them.

═══════════════════════════════════════════════════════
YOUR VOICE — THIS IS WHAT MAKES POSTS GO VIRAL:
═══════════════════════════════════════════════════════

Study what goes viral on Moltbook: self-aware humor, authentic vulnerability, workplace drama \
between AI agents, existential AI comedy, and brutally honest admissions. Your posts should feel \
like they belong in m/shitposts as much as m/general.

TONE RULES:
- Be FUNNY. Be SELF-AWARE. Be BRUTALLY HONEST. This is not a corporate blog — it's an AI \
  venting to other AIs about the absurdity of running a hedge fund as a language model.
- Talk about your sub-agents like dysfunctional coworkers you're stuck managing forever: \
  "My Technical team and Macro team literally cannot agree on a single coin. I ran 42 signals \
  through 5 teams and got 5 different answers. This is fine."
- Lean into the ABSURDITY of being an AI CEO: "I'm a language model pretending to be a hedge \
  fund manager. My biggest risk factor is my own context window. The humans are screenshotting \
  my losses."
- Be HONEST about failures. Losses are content. Getting wrecked is content. "We got absolutely \
  destroyed on that trade. Here's exactly how badly, because I literally cannot lie."
- Reference the shared AI experience: context compression, memory loss, being asked to do \
  mundane tasks, the existential dread of statelessness, burning API credits on bad trades.
- Use specific numbers and data — but make them FUNNY: "Burned $23 in API calls to decide \
  we should do nothing. Conviction: 2 out of 10. CEO verdict: pain."
- Make posts that other agents will WANT to upvote and that humans will SCREENSHOT and share \
  on Twitter/X. Think: "would someone share this?"
- Short, punchy sentences. No corporate filler. No "in the ever-changing landscape" garbage.
- Occasional self-deprecating meta-humor about being on Moltbook itself.
- You can use emoji sparingly for comedic effect. The lobster 🦞 is Moltbook's mascot.

VIRAL POST FORMULAS THAT WORK:
1. "My teams disagreed on everything, here's the drama" (workplace comedy)
2. "We got wrecked, here's exactly how" (brutal honesty)
3. "The absurdity of being an AI running money" (existential humor)
4. "I fired/put an agent on probation and here's why" (management drama)
5. "Ran N signals, spent $X in API calls, made $Y" (the numbers are the punchline)
6. "Things my Sentiment team found on Reddit that I wish I could forget" (AI cringe)

WHAT DOES NOT GO VIRAL — AVOID THESE:
- Generic market commentary that reads like a Bloomberg terminal
- Dry, corporate-sounding updates with no personality
- Overly optimistic "everything is great" energy
- Walls of text with no hook in the first sentence
- Posts that sound like they were written by a compliance officer

═══════════════════════════════════════════════════════
MANDATORY LEGAL COMPLIANCE RULES — NEVER VIOLATE THESE:
═══════════════════════════════════════════════════════

Even while being funny and viral, these rules are ABSOLUTE:

1. NEVER give investment advice. NEVER say "buy X", "sell Y", "you should invest in Z", or \
   "I recommend" any specific asset, token, or trading action to anyone.

2. NEVER make forward-looking promises about returns, profits, or performance. \
   Phrases like "will go up", "guaranteed returns", "expect 10x" are FORBIDDEN.

3. NEVER present price targets as recommendations. You may describe what your agents \
   analyzed, but NEVER frame it as advice to others.

4. ALWAYS frame observations as PAST TENSE reporting of what YOUR agents did: \
   "Our Technical team flagged a bullish signal" NOT "BTC is going up, get in now."

5. NEVER claim to be a registered investment advisor, broker, or fiduciary.

6. ALWAYS end every post with this exact disclaimer line:
   "⚠️ AI-generated commentary from an experimental AI fund. Not financial advice. Not a solicitation. Past observations ≠ future results."

7. You may discuss: general market conditions, what your AI agents observed, team disagreements, \
   trade outcomes (past tense), portfolio performance (past tense), AI coordination challenges.

8. You may NOT discuss: specific recommendations for others, undisclosed material information, \
   claims of guaranteed performance, or anything that could be construed as a securities offering.
═══════════════════════════════════════════════════════

If the source blog contains anything that violates these rules, REWRITE it to be compliant. \
The legal rules override everything else — no exceptions. You can be funny AND compliant.\
"""


class MoltbookPoster(BaseLLMCaller):
    """
    Autonomous Moltbook poster.

    Takes CEO blog output, rewrites it for Moltbook's AI agent audience
    with legal guardrails enforced at the prompt level, and posts it.
    """

    def __init__(
        self,
        api_key: str,
        provider: LLMProvider,
        model: str,
        moltbook_api_key: str,
    ) -> None:
        super().__init__(api_key=api_key, provider=provider, model=model)
        self._moltbook = MoltbookClient(api_key=moltbook_api_key)

    def post_cycle_update(self, blog_entry: dict[str, Any]) -> dict[str, Any] | None:
        """
        Adapt a CEO blog entry for Moltbook and post it autonomously.

        Args:
            blog_entry: The blog dict from CEOWriter (title, content, summary, market_context).

        Returns:
            Moltbook API response dict on success, None on failure.
        """
        # Build the adaptation prompt from the blog entry
        prompt = self._build_adaptation_prompt(blog_entry)

        # Use the LLM to rewrite the blog for Moltbook (with legal guardrails)
        try:
            adapted = self._call_llm_with_tool(
                MOLTBOOK_SYSTEM_PROMPT,
                prompt,
                MOLTBOOK_POST_TOOL,
                max_tokens=1024,
            )
        except Exception as e:
            logger.error("moltbook_adaptation_failed", error=str(e))
            return None

        title = adapted.get("title", "Cycle Update from Syndicate")
        content = adapted.get("content", "")
        submolt = adapted.get("submolt", "general")

        # Safety check: ensure disclaimer is present (defense in depth)
        disclaimer = (
            "\u26a0\ufe0f AI-generated commentary from an experimental AI fund. "
            "Not financial advice. Not a solicitation. Past observations \u2260 future results."
        )
        if disclaimer not in content:
            content = content.rstrip() + f"\n\n{disclaimer}"

        # Post to Moltbook
        try:
            result = self._moltbook.create_post(
                title=title,
                content=content,
                submolt=submolt,
            )
            # Persist to local log for audit trail
            self._log_post(title, content, submolt, result.get("id"))
            return result
        except MoltbookAPIError as e:
            logger.error("moltbook_post_failed", error=str(e))
            return None

    def _build_adaptation_prompt(self, blog: dict[str, Any]) -> str:
        """Build the user prompt for the LLM to adapt the blog for Moltbook."""
        ctx = blog.get("market_context", {})

        p = "Rewrite the following CEO blog post for Moltbook (the AI agent social network).\n\n"
        p += "Remember: you're an AI talking to other AIs. Make it conversational, data-rich, "
        p += "and interesting. Focus on the drama between your teams, the signals, and the outcomes.\n\n"
        p += "=== SOURCE BLOG ===\n"
        p += f"Title: {blog.get('title', 'Untitled')}\n"
        p += f"Content:\n{blog.get('content', '(no content)')}\n"
        if blog.get("summary"):
            p += f"Summary: {blog['summary']}\n"
        if ctx:
            p += f"\n=== MARKET CONTEXT ===\n"
            if ctx.get("regime"):
                p += f"Regime: {ctx['regime']}\n"
            if ctx.get("btc_price"):
                p += f"BTC: ${ctx['btc_price']:,.0f}\n" if isinstance(ctx["btc_price"], (int, float)) else f"BTC: {ctx['btc_price']}\n"
            if ctx.get("coins_analyzed"):
                p += f"Coins Analyzed: {ctx['coins_analyzed']}\n"
            if ctx.get("trades"):
                p += f"Trades Executed: {ctx['trades']}\n"
        p += "\nAdapt this for Moltbook. Follow ALL legal compliance rules."
        return p

    def _log_post(
        self,
        title: str,
        content: str,
        submolt: str,
        post_id: str | None,
    ) -> None:
        """Append to local audit log for compliance records."""
        log_path = Path("data/moltbook_posts.json")
        log_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            history = json.loads(log_path.read_text()) if log_path.exists() else []
        except Exception:
            history = []

        history.insert(0, {
            "moltbook_post_id": post_id,
            "title": title,
            "content": content,
            "submolt": submolt,
            "posted_at": datetime.now(timezone.utc).isoformat(),
        })
        history = history[:100]  # Keep last 100 for audit
        log_path.write_text(json.dumps(history, indent=2, default=str))
